### ISSUE TITLE
Install fail with lazy

### ISSUE THREAD

**Issue by towry** [hoschi/yode-nvim#13]
<img width="1096" alt="截屏2023-01-02 17 21 48" src="https://user-images.githubusercontent.com/8279858/210213140-aeee415b-0a85-484c-a812-88e416334436.png">

fails on develop or master branch.

**Comment by hoschi** [comment]
Can you elaborate what Lazy is and what you tried to do?

**Comment by towry** [comment]
@hoschi 
https://github.com/folke/lazy.nvim

What is lazy: Lazy.nvim package manager.
What I was trying to do: install this plugin with lazy.

**Comment by hoschi** [comment]
I changed the doc file, please try again with the develop branch @towry

**Comment by towry** [comment]
Issue is gone, thanks.

**Comment by hoschi** [comment]
Great! I release master then.
