### ISSUE TITLE
The floating window is not expandable

### ISSUE THREAD

**Issue by jonahfang** [hoschi/yode-nvim#17]
I use this plugin with Lazy.nvim:

```
return {
  "hoschi/yode-nvim",
  keys = {
     {',n', "<cmd>YodeCreateSeditorFloating<cr>",mode={'n','x'}},
  },
  config = function()
      require('yode-nvim').setup({})

      vim.cmd([[
        set showtabline=2
      ]])
  end
}
-- EOP
```

When I selected more than one lines and press ',n', the floating window was only one line height and show the last line like this:

<img width="578" alt="image" src="https://github.com/hoschi/yode-nvim/assets/16301509/54c8be9c-1d86-431b-9e3a-a3a55cb6855d">

**Comment by hoschi** [comment]
That is expexted. Without a range specified, it defaults to 1. You need to either use visual mode or type in a count before issuing it in normal Mode.

**Comment by jonahfang** [comment]
@hoschi , thanks for reply. Could you explain more detail?

**Comment by hoschi** [comment]
Type `10,n` which should create a ten line seditor. Does this work with your setup?

**Comment by jonahfang** [comment]
Where to put 10,n ?

**Comment by jonahfang** [comment]
I has solved this problem, same as <https://github.com/hoschi/yode-nvim/issues/9>, use `:` to replace `<cmd>` and it works!
