### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by vizcay** [hoschi/yode-nvim#3]
Hey, saw your post on reddit and I though this plugin will be interesting to have! Nice work = )

Creating floats was easy as getting out of them with (with `C-w + ..`)  but I did struggle a little to navigate back to them until I've found `C-w C-w` online.. maybe you will want to add that to the README and docs. 

Why the need for `YodeBufferDelete` when we have `C-w + c`?

Also, I think that `YodeBufferDeleteAll` will be nice to have.

**Comment by timoleistner** [comment]
Thank you @vizcay for the `C-w C-w` this is what I missed.
Also, is it yet possible to visually select lines and send them into the floating window with a keymap?
So far I can only send single lines except when I manually enter the `YodeCreateSeditorFloating` command after visually selecting.
I tried to translate these mappings to lua but this didnt work out.
```
local map = vim.api.nvim_set_keymap -- keymap
map('n', 'yc', '<CMD>YodeCreateSeditorFloating<CR>', { noremap = true })
map('v', 'yc', "<CMD>YodeCreateSeditorFloating<CR>", { noremap = true })
```
Anyone an idea?
Very nice plugin indeed :)

**Comment by hoschi** [comment]
@vizcay good point, I add a link to window movement. You can close a window and the seditor is still there, check `:buffers`. You can delete a seditor and it would delete the seditor and the window. `YodeBufferDelete` is to delete the buffer *and* jump back to the file.

@timoleistner I don't get what you can't achive with the mapping from the Readme:
`map <Leader>yc      :YodeCreateSeditorFloating<CR>`
With this you can visually select lines and press `,yc` like I do in the introduction video.

**Comment by hoschi** [comment]
@timoleistner please create a new issue if you still have problems

**Comment by lucax88x** [comment]
@hoschi 
interesting.

using 

```lua
vim.cmd('map <Leader>yc :YodeCreateSeditorFloating<CR>')
```

range selection works,

but using

```lua
vim.keymap.set('', '<Leader>yc', '<CMD>:YodeCreateSeditorFloating<CR>', { remap: true})
```

does not, uses only last line, in theory the two commands should be equivalent.. am I wrong?

**Comment by hoschi** [comment]
I don't know 🤔

**Comment by vizcay** [comment]
@lucax88x this worked for me:

```vim.api.nvim_set_keymap("v", "<Leader>f", ":YodeCreateSeditorFloating<CR>", {noremap = true})```

**Comment by lucax88x** [comment]
Silly me, problem was using ```<CMD>``` at beginning, removing it worked.
