### ISSUE TITLE
Corrupt mp4 files in README

### ISSUE THREAD

**Issue by maxmahlke** [hoschi/yode-nvim#4]
The example GIFS in the README do not play at all for me, Firefox says the files are corrupt.

**Comment by kasbah** [comment]
Same, Firefox 93 on Linux.

![](https://i.imgur.com/DgQLXqj.png)

Is probably more of a Github or Firefox issue, looking at console while viewing the file shows:


```
Media resource https://user-images.githubusercontent.com/163128/153627026-e346eb0c-b7e9-4bef-986f-79cb64dadfac.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.
```

**Comment by hoschi** [comment]
I uploaded them to Yotube and added links to each section.

**Comment by chris-morgan** [comment]
Nothing is playing it for me under Linux: Firefox says it’s corrupt or an unsupported codec, VLC crashes (!!), qtav `Player` calls it “invalid media”.

In this case, it comes down to the use of full 4:4:4 chroma, which is poorly supported. In https://stackoverflow.com/a/37969294 comments, mid 2016 say the web only supports 4:2:0, and late 2021 says Chrome now supports 4:4:4 (and I can actually confirm that with Chromium now that I try it—it’s the only thing I’ve found on my system that will *play* the 4:4:4 videos). Changing it from yuv444p to yuv420p with `ffmpeg -i in.mp4 -pix_fmt yuv420p out.mp4` makes it work.

Unfortunately with .mp4 being a container format, not all .mp4s are created equal.

**Comment by hoschi** [comment]
I updated everything and tested it, for me it works now in Firefox as well. Thanks again, @chris-morgan

**Comment by VladBrok** [comment]
@hoschi could you please tell what exactly did you change in order to make your videos work in Firefox?

**Comment by hoschi** [comment]
@VladBrok my notes say I did these steps:

* create small GIF-like files
	* make GIF with Peek and save it as `in.gif`
	* convert to mp4 `ffmpeg -i in.gif out.mp4`
	* make it faster `ffmpeg -i out.mp4 -filter:v "setpts=0.2*PTS" out-fast.mp4`
	* make it web compatible `ffmpeg -i out-fast.mp4 -pix_fmt yuv420p out-web.mp4`
	* open `Readme.md` in Github and add file via drag/drop

**Comment by VladBrok** [comment]
@hoschi thank you very much for help!
