### ISSUE TITLE
Error detected while processing BufEnter Autocommands

### ISSUE THREAD

**Issue by slashv** [hoschi/yode-nvim#5]
This is an excellent idea and really want to use the plugin but when I install it I get this error:

Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...e/nvim/plugged/yode-nvim/lua/yode-nvim/changeSyncing.lua:568: attempt to index local 'log' (a function value)
stack traceback:
        ...e/nvim/plugged/yode-nvim/lua/yode-nvim/changeSyncing.lua:568: in function 'subscribeToBuffer'
        [string ":lua"]:1: in main chunk

nvim --version
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by hoschi** [comment]
Do you have Plenary installed? Can you try with minimal version of your configuration?

**Comment by hoschi** [comment]
Ah, got it. You must have forgotten to set up the plugin. When I remove the `lua require('yode-nvim').setup({})` call I get the same error.

**Comment by kellpossible** [comment]
No other plugins I've used  cause errors like this when you don't call the setup function though

**Comment by hoschi** [comment]
found a way and comitted a fix

**Comment by slashv** [comment]
Ah, my bad for not calling setup. Thanks for figuring it out and committing a fix that solves it for new users by default.
