### ISSUE TITLE
Not working with Harpoon

### ISSUE THREAD

**Issue by 3bdallahz** [hoschi/yode-nvim#6]
Hi,
I'm using harpoon, when I use yode to create a view of particular lines, I can add that view to harpoon, but when I close and reopen vim I can see the view in harpoon list, but when I open it I don't see anything.

if I'm on a view of code, Can I go to where it's defined?
How can add selected lines to yode without showing the floating window?
Can I see/view the list of yode snippets all at once?

something I have in mind is when I select a range of lines, I want to add them directly to harpoon, instead of creating a view then moving to the floating window and then add to harpoon

**Comment by hoschi** [comment]
>  when I close and reopen vim

This isn't supported yet, see also #7 

> if I'm on a view of code, Can I go to where it's defined?

Through the API, have a look at my fork of Neomake in the Readme o see usage examples.

> How can add selected lines to yode without showing the floating window?

`:YodeCreateSeditorReplace`

> Can I see/view the list of yode snippets all at once?

You can filter Neovims buffer list or also use the API.

If you got Harpoon working with Yode-Nvim, please link the solution in #2

**Comment by 3bdallahz** [comment]
Thanks @hoschi

**Comment by hoschi** [comment]
@abdallahz3 do you still have problems? if not, please close the issue

**Comment by 3bdallahz** [comment]
sure, Thanks @hoschi for an amazing plugin
