### ISSUE TITLE
Mapping with `<Cmd>` instead of `:` don't work

### ISSUE THREAD

**Issue by diegodox** [hoschi/yode-nvim#9]
This plugin's demo blow my mind, awesome.

But, I'm not sure how to setup this plugin.
My setting is below.
```lua
require('yode-nvim').setup()
```
and
```vim
vnoremap <Space>yc <Cmd>YodeCreateSeditorFloating<CR>
```

Just after selecting lines in `<C-v>`(visual lines) mode, I expect `<Space>yc` to create yode's floating buffer with lines I select. But, it create yode's floating buffer only with one line which my cursor is placed.

How to create yode's buffer with all selected lines?

**Comment by hoschi** [comment]
Glad you like it! This one is the mapping from the Readme with `<Leader>` replaced by `<Space>` and should work:
`map <Space>yc      :YodeCreateSeditorFloating<CR>`

Can you try it?

**Comment by diegodox** [comment]
Thank you for your advice.

I tried ~~`map <Space>yc :YodeCreateSeditorFloating<CR>`~~. I still not get all selected lines, only get cursor line.

_**EDIT**_: Sorry I tried `map <Space>yc <Cmd>YodeCreateSeditorFloating<CR>`. It should be fixed if I tried `:` instead of `<Cmd>`.


I think I should try other plugins uninstalled.


<details>
<summary>
List of the plugins I have installed.
Do you have any ideas for other plugins that would prevent this plugin from working?
</summary>

Your plugin.
- yode-nvim
- plenary.nvim

Maybe one of these?
- coc.nvim
- which-key.nvim

I think they are not related.
- winresizer
- winshift.nvim
- copilot.nvim
- dein (package manager)
- vim-startify
- vim-rooter
- lualine.nvim
- Comment.nvim
- vim-devicons
- nvim-tree.lua
- rnvimr
- lazygit.nvim
- nvim-treesitter
- nvim-treesitter/playground
- indent-blankline.nvim
- nvim-ts-rainbow
- telescope.nvim
- vim-fugitive
- gitsigins.nvim
- close-buffers.nvim
- undotree
- gruvbox
- vim-code-dark
- telescope-coc.nvim
- nvim-notify
- neoscroll.nvim
- crates.nvim
- octo.nvim
</details>

**Comment by hoschi** [comment]
I don't see any problematic plugin that catches my eye. Can you execute `:map <Space>yc` and paste the output/screenshot?

**Comment by diegodox** [comment]
Here is my output for `:map <Space>yc`.
![temp](https://user-images.githubusercontent.com/37207872/159464074-dc734e7d-1362-4118-b2f1-e076adeed59d.png)

**Comment by hoschi** [comment]
Please try to disable "which-key". Also this `<Cmd>` thing is something I didn't see before.

**Comment by diegodox** [comment]
I found my mistake. Use `:` instead of `<Cmd>` fix this problem which I found on [other issue](https://github.com/hoschi/yode-nvim/issues/3#issuecomment-1038303467) on this plugin.

**Comment by diegodox** [comment]
Help for someone who meet same problem, difference between `<Cmd>` and `:` from `help <Cmd>`.

Both execute command, but `<Cmd>` doesn't change mode.

> The <Cmd> pseudokey begins a "command mapping", which executes the command
directly (without changing modes).

**Comment by diegodox** [comment]
I close this issue. Thank you @hoschi.

**Comment by hoschi** [comment]
Interesting, glad you could solve the problem. I'll adjust the title in case anyone else is looking for the problem.
